# Generated by Django 2.0.2 on 2019-03-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
                'indexes': [],
            },
            bases=('course.course',),
        ),
    ]
