# Generated by Django 2.0.2 on 2019-03-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_bannercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerCourse',
        ),
    ]
